spring.application.name=crop-price-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/farmer_db
spring.datasource.username=postgres
spring.datasource.password=5509

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081